name: Run test suite

on: push

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - run: npm i -g @angular/cli@v13-lts
      - run: npm ci
        working-directory: ngx-fudis
      - run: ng test npx-fudis --watch false --browsers ChromeHeadless
        working-directory: ngx-fudis

  publish:
    name: Publish ngx-fudis
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - run: npm i -g @angular/cli@v13-lts
      - run: npm ci
        working-directory: ngx-fudis
      - run: ng build ngx-fudis
        working-directory: ngx-fudis
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ngx-fudis/dist/ngx-fudis/package.json
          tag: latest
