name: Publish NPM package

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/test.yaml

  publish:
    name: Publish ngx-fudis to NPM
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - name: Install Angular CLI
        run: npm i -g @angular/cli@v13-lts
      - name: Install dependencies
        run: npm ci
        working-directory: ngx-fudis
      - name: Build ngx-fudis
        run: ng build ngx-fudis
        working-directory: ngx-fudis
      - name: Publish @funidata/ngx-fudis
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ngx-fudis/dist/ngx-fudis/package.json
          access: public
          tag: latest
