name: Release new version

on:
  release:
    types:
      - released

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml

  publish:
    name: Publish library to NPM
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build ngx-fudis
        run: npm run build
      - run: npm publish --access public
        working-directory: ngx-fudis/dist/ngx-fudis
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
