name: Release new version

on:
  release:
    types:
      - released

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml

  publish:
    name: Publish library to NPM
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Recent Node.js is included in `ubuntu-latest` but `setup-node` is still required to setup NPM auth via token.
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          # Specifying `registry-url` triggers `setup-node` to setup NPM authentication.
          registry-url: https://registry.npmjs.org/
      - name: Copy root README.md to library
        run: cp README.md ngx-fudis/projects/ngx-fudis/README.md
      - name: Build ngx-fudis
        run: npm run build
      - run: npm publish --access public
        working-directory: ngx-fudis/dist/ngx-fudis
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
