name: Release new version

on:
  release:
    types:
      - released

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml

  publish:
    name: Publish image
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14
          registry-url: https://registry.npmjs.org/
      - name: Install Angular CLI
        run: npm i -g @angular/cli@v16
      - name: Install dependencies
        run: npm ci
        working-directory: ngx-fudis
      - name: Build ngx-fudis
        run: ng build ngx-fudis
        working-directory: ngx-fudis
      - name: Build library schematics
        run: npm ci && npm run build
        working-directory: ngx-fudis/projects/ngx-fudis
      - run: npm publish --access public
        working-directory: ngx-fudis/projects/ngx-fudis
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
