name: Run tests

on:
  # Enable reusing this workflow.
  workflow_call:
  # Run after PR is merged to main.
  push:
    branches:
      - main
  # Run for PR's. External PR's require approval before running checks.
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build_image.yaml

  lint:
    name: Linting
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fudis-test
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/fudis-test.image.tar
      - name: Run linter
        run: docker run -t fudis-test npm run lint
        continue-on-error: true

  component-tests:
    name: Component tests
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fudis-test
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/fudis-test.image.tar
      - name: Run unit tests
        run: docker run -te CI=true fudis-test npm test
