name: Run tests

on:
  # Enable reusing this workflow.
  workflow_call:
  # Run after PR is merged to main.
  push:
    branches:
      - main
  # Run for PR's. External PR's require approval before running checks.
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build_image.yaml

  lint:
    name: Run linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Install Angular CLI
        # TODO: Would be nice to get this version from package.json rather than hardcoding it here...
        run: npm i -g @angular/cli@v16
      - name: Install dependencies
        run: npm ci
        working-directory: ngx-fudis
      - name: Run linter
        run: ng lint
        working-directory: ngx-fudis

  component-tests:
    name: Component tests
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fudis-test
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/fudis-test.image.tar
      - name: Run unit tests
        run: docker run -te CI=true fudis-test npm test
