name: Run test suite

on:
  push:
    branches-ignore:
      - main
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - name: Install Angular CLI
        run: npm i -g @angular/cli@v13-lts
      - name: Install dependencies
        run: npm ci
        working-directory: ngx-fudis
      - name: Run tests
        run: ng test ngx-fudis --watch false --browsers ChromeHeadless
        working-directory: ngx-fudis
